name: titanic-mlflow
channels:
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - mlflow==2.18.0
  - dagshub
  - scikit-learn
  - pandas
  - matplotlib
  - joblib
  - cloudpickle
  - numpy
  - seaborn
