name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.18.0
      - pandas
      - scikit-learn == 1.5.2
      - matplotlib
      - seaborn