name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - scikit-learn=1.5.2
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - mlflow
      - dagshub